
tasks:
- source: scripts/get.py
  product:
    data: products/get.csv
    nb: products/get.ipynb
  
- source: scripts/eda.py
  product:
    nb: products/eda.ipynb

- source: scripts/features.py
  product: 
    nb: products/features.ipynb

- source: scripts/models.py
  product: 
    nb: products/models.ipynb


